### PR TITLE
Update to 0.10.3

### PR DESCRIPTION
**Pull request by negberts**

### CODE REVIEW

**Comment by negberts** [comment]
I am sorry, still trying to figure out how I can merge your master with my master...

**Comment by DxCx** [comment]
@negberts please note that the package is deprecated since xlsx 0.10.3 is released with typings,
please try to replace ts-xlsx with xlsx and report back.

cc @SheetJS

**Comment by negberts** [comment]
@DxCx I'm trying.. But we are using systemjs and when I include dist/xlsx.full,min.js I get an error in the app saying function read is not found.
Including anything else like xlsx.js gives a path error to cpexcel.

**Comment by DxCx** [comment]
since xlsx is trying to get typescript supported i believe the right thing to do is to solve this issue within js-xlsx.
i don't mind help debug and find the solution but i think it should be submitted to https://www.github.com/SheetJS/js-xlsx and not in here.

**Comment by SheetJSDev** [comment]
@negberts I'm not too well-versed in systemjs but the following appears to work against xlsx 0.10.3:

## Browser

Download the systemjs dist, extract, save the following HTML:

```html
<script src="systemjs/dist/system.js"></script>
<script>
	SystemJS.config({
		meta: {
			'xlsx': {
				exports: 'XLSX' // <-- this is needed to tell SystemJS to expose XLSX
			}
		},
		map: {
			'xlsx': 'node_modules/xlsx/dist/xlsx.full.min.js',
			'fs': '', // <-- systemjs doesn't seem to automatically suppress node core
			'crypto': '', 
			'stream': ''
		}
	});
  SystemJS.import('main.js');
</script>
```

Then save the following to main.js:

```js
var XLSX = require('xlsx');
console.log(XLSX);
var w = XLSX.read('abc,def\nghi,jkl', {type:'binary'});
var j = XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]], {header:1});
console.log(j);
```

## NodeJS

```js
var SystemJS = require('systemjs');
SystemJS.config({
	map: {
		'xlsx': 'node_modules/xlsx/xlsx.js',
		'fs': '@node/fs',
		'crypto': '@node/crypto',
		'stream': '@node/stream'
	}
});
SystemJS.import('xlsx').then(function(XLSX) {
	var w = XLSX.readFile('test.xlsx');
	var j = XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]], {header:1});
	console.log(j);
});
```

Please test if the config works.

**Comment by negberts** [comment]
Thanks for helping out. I've tried the NodeJS version earlier today and then received an error that it could not find http://localhost/@node/fs during application load so I aborted that path. Will give it another try tomorrow or otherwise next week. Keep you posted!

**Comment by DxCx** [comment]
@SheetJSDev maybe we should use webpack/rollup to bundle it better?

**Comment by negberts** [comment]
That would probably help a lot of people. For now I got it working in my dev build. Still trying to deploy a prod build. Hopefully that works too :)

**Comment by negberts** [comment]
I cannot get it to work in my prod/AOT build. If I include the xlsx.js file it complains about missing fs during AOT build and if I include xlsx.full.min.js the build is okay but during runtime I get errors like below when trying to upload a excel document. 

```
TypeError: Pc is not a constructor
    at Xl (app.js?1495191022910:80)
    at Object.Ql [as read] (app.js?1495191022910:80)
    at FileReader.<anonymous> (app.js?1495191022910:25)
    at e.invokeTask (shims.js?1495191022907:3)
    at Object.onInvokeTask (app.js?1495191022910:95)
    at e.invokeTask (shims.js?1495191022907:3)
    at r.runTask (shims.js?1495191022907:3)
    at FileReader.invoke (shims.js?1495191022907:3)

```
 So a bundle like ts-xlsx was supplying would be very helpful. Until then I will keep using this library.

**Comment by DxCx** [comment]
@negberts would you like to get contributer access here so you can upgrade it it and use it?
the last thing i want to do is to hold your production..
however,
i still think we should all aim moving towards using 1 library in the future.. i had to create this one because of the issues you mentioned above for example..

**Comment by SheetJSDev** [comment]
@negberts can you share your webpack or systemjs config?  I tested the scenarios in https://github.com/DxCx/ts-xlsx/pull/17#issuecomment-302437062 as well as the webpack demo in the main repo https://github.com/SheetJS/js-xlsx/tree/master/demos/webpack and they seem to work, so if it's not working in your build it means our demos are probably doing something nonstandard

**Comment by negberts** [comment]
I think I have it working. For my dev build I needed xlsx.js in my systemjs.config of NodeJS, but for the production build, which bundles all the modules into app.js I needed dist/xlsx.full.min.js :)

**Comment by DxCx** [comment]
great, so can we close this @negberts ?

**Comment by negberts** [comment]
Yes indeed!

**Pull request closed without merging**
